### ISSUE TITLE
Error in guess_bonds() 

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/PLAMS#12]
I'm trying to guess_bonds() for this xyz:
```
10

H -0.00126 1.83437 -1.35474
N -0.02562 -0.34660 1.17301
H -0.92656 -0.59522 1.58997
N 0.18942 -1.17915 0.00000
H 1.19591 -1.34432 0.00000
N -0.02562 -0.34660 -1.17301
H -0.92656 -0.59522 -1.58997
C -0.02562 0.99771 0.66854
C -0.02562 0.99771 -0.66854
H -0.00126 1.83437 1.35474
```
It crashes with the following error:
```
>>> import plams
>>> mol = plams.Molecule("ref_structures/ac10_product.xyz")
>>> mol.guess_bonds()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lars/workspace/plams/src/scm/plams/core/basemol.py", line 731, in guess_bonds
    val, o, r, at1, at2 = heapq.heappop(heap)
TypeError: unorderable types: Atom() < Atom()
```

**Comment by h4nsu** [comment]
Meh, it turns out comparison works in a bit different way in Python 3 than in Python 2. Will fix asap. Thanks for catching this!

**Comment by ridderl** [comment]
Thanks!
