### ISSUE TITLE
Reading molfile fails

### ISSUE THREAD

**Issue by ridderl** [SCM-NV/PLAMS#22]
I'm trying to read the following molfile:
```
C-N-C
     RDKit          3D

 14 14  0  0  0  0  0  0  0  0999 V2000
   -2.5643    0.9533    3.7345 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6268   -0.0105    3.7867 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4054    0.0088    3.2202 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3552    0.3486    0.9210 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5775    0.8918    1.1848 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2363   -0.7165    0.7254 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4990    0.9749    0.6713 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.4779    0.2795    1.2186 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7358    1.9699    1.1655 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.5236    0.7392    4.1952 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2306    1.9815    3.6419 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9770   -0.9380    4.0199 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1985   -0.8881    3.3179 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0821    0.9710    3.1028 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  1  1  0
  4  6  1  0
  4  7  1  0
  5  8  1  0
  5  9  1  0
  1 10  1  0
  1 11  1  0
  2 12  1  0
  3 13  1  0
  3 14  1  0
M  END
```
Which fails as follows:
```
>>> from scm.plams import Molecule
>>> m = Molecule('molfile.mol')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lars/workspace/plams/src/scm/plams/core/basemol.py", line 410, in __init__
    self.read(filename, inputformat, geometry)
  File "/home/lars/workspace/plams/src/scm/plams/core/basemol.py", line 1430, in read
    ret = self._readformat[inputformat](self, f, frame)
  File "/home/lars/workspace/plams/src/scm/plams/core/basemol.py", line 1215, in readmol
    self.add_atom(Atom(atnum=num, coords=crd))
UnboundLocalError: local variable 'crd' referenced before assignment
```
If I change `crdx` to `crd` in line 1205 of basemol.py, it still fails, because the atom symbols are not written to the input file.

**Comment by h4nsu** [comment]
Is it ok now?
