### ISSUE TITLE
No plams module after installation...

### ISSUE THREAD

**Issue by miroi** [SCM-NV/PLAMS#26]
Dear all,

I installed plams as user, but plams module did not appear to be present. Any help, please ?

~~~
milias@login.grid.umb.sk:~/.pip install --user plams
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6                                                                                                                                                    
Collecting plams
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading PLAMS-1.1.1-py2.py3-none-any.whl (76kB)
    100% |################################| 81kB 936kB/s 
Collecting dill>=0.2.4 (from plams)
  Downloading dill-0.2.7.1.tar.gz (64kB)
    100% |################################| 71kB 1.4MB/s 
Requirement already satisfied: six in /usr/lib/python2.6/site-packages (from plams)
Requirement already satisfied: numpy in /usr/lib64/python2.6/site-packages (from plams)
Installing collected packages: dill, plams
  Running setup.py install for dill ... done
Successfully installed dill-0.2.7.1 plams-1.1.1
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
milias@login.grid.umb.sk:~/.plams
-bash: plams: command not found
milias@login.grid.umb.sk:~/.s
Source of the /home/milias/.bashrc file on login done.
Welcome to login.grid.umb.sk (172.20.102.32) HPC server at Matej Bel University !
Intel Fortran/C/C++ commercial compilers with MKL library activated, PROD_DIR=/mnt/apps/intel/composer_xe_2013_sp1.
The $PYTHONPATH already contains "/home/milias/bin/PyADF/PyADF-0.9/src".
The $LIBDIR already contains "/home/milias/bin/binutils-gold/lib".
The $LD_RUN_PATH already contains "/home/milias/bin/binutils-gold/lib".
Directory "/shared/home/ilias/bin/binutils-gold/bin" does not exist! No extension of $PATH.
Personal file /home/milias/miro_ilias_bashrc/bashrc_generic does exist !
It comes from "git clone deveo@app.deveo.com:miroslaviliasumbsk/projects/miro_ilias_working_repos/repositories/git/miro_ilias_bashrc" 
Personal bashrc linked :lrwxrwxrwx 1 milias milias 45 Feb 16  2015 /home/milias/.bashrc -> /home/milias/miro_ilias_bashrc/bashrc_generic
$PATH already contains "."
milias@login.grid.umb.sk:~/.python
Python 2.7.12 (default, Dec 14 2016, 21:53:57) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import plams
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named plams
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
>>> 
~~~

**Comment by h4nsu** [comment]
Please try `import scm.plams`

**Comment by miroi** [comment]
The problem is that we don't have python 3 on our server.
The plams library still not visible....
~~~
milias@login.grid.umb.sk:~/.ls .local/lib/python2.6/site-packages/PLAMS-1.1.1.dist-info/
DESCRIPTION.rst  INSTALLER  METADATA  RECORD  WHEEL  metadata.json  namespace_packages.txt  top_level.txt
.
.
.
milias@login.grid.umb.sk:~/.python 
Python 2.7.12 (default, Dec 14 2016, 21:53:57) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scm.plams
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named scm.plams
~~~

**Comment by miroi** [comment]
Well,

this works on other machine, pip install --user plams. 

On login.grid.umb.sk we have some hacks wrt to Python... closing this ticket.

~~~
milias@lxg1221.gsi.de:~/Work/qch/software/My_scripts/local_runs/gsi_de/lxir_nodes/dirac/dirac4grid_runs/.python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scm.plams
>>> 
~~~

**Comment by h4nsu** [comment]
~~~
milias@login.grid.umb.sk:~/.ls .local/lib/python2.6/site-packages/PLAMS-1.1.1.dist-info/
DESCRIPTION.rst  INSTALLER  METADATA  RECORD  WHEEL  metadata.json  namespace_packages.txt  top_level.txt
.
.
.
milias@login.grid.umb.sk:~/.python 
Python 2.7.12 (default, Dec 14 2016, 21:53:57) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scm.plams
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named scm.plams
~~~
These are two different Pythons! In the first line you list a package installed in Python 2.6, and then you start Python 2.7.12
